name: test deploy
on:
    push:
        branches: [main]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-18.04

        steps:
            - name: Deploy to Server
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /root
                      ./deploy.sh
